server:
  port: 8080

spring:
  application:
    name: gateway-spring
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
      routes:
        - id: user-service
          uri: http://user-api:8082
          predicates:
            - Path=/api/v1/usuarios/**